apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "quizfrontend.fullname" . }}
  annotations:
    alb.ingress.kubernetes.io/group.name: "quizzer-alb"
spec:
  rules:
    - host: quizzes.kmflow.org # Your custom domain
      http:
        paths:
          - path: /create
            pathType: Prefix
            backend:
              service:
                name: quizcrud
                port:
                  number: 80
